### ISSUE TITLE
Normalize countries

### ISSUE THREAD

**Issue by pyrog** [kerel-fs/ogn-rdb#14]
I suggest to use an official code for country ([ISO 3166](https://en.wikipedia.org/wiki/ISO_3166-1#Current_codes), ICAO…) to easily add translations, sharing datas across projects, display [country flag](https://github.com/adamoliver/Country-Flags-ISO-3), match easily aircraft /airport register code and country…

Could be done in [wikidotparser.py#L84-L113](https://github.com/kerel-fs/ogn-rdb/blob/master/wikidotparser.py#L84-L113)

**Comment by kerel-fs** [comment]
Jup, this is planned for a long time.
