### ISSUE TITLE
Specify python version

### ISSUE THREAD

**Issue by pyrog** [kerel-fs/ogn-rdb#18]
Code in PR #9 is written for Python 2.7.12
Code submitted in e8d8cb2a537762ee3b8224b04474b91200ab5fc8 is written for Python ≥ 3 😉 

Could you document which version Python is required in the project ?
Or use a package management system like [conda](http://conda.pydata.org/docs/index.html) ?

Thanks 😄 

```
Traceback (most recent call last):
  File "mkreceiverjson.py", line 61, in <module>
    with open(ARGS.out_file, 'w', encoding='utf-8') as f:
TypeError: 'encoding' is an invalid keyword argument for this function

```

**Comment by kerel-fs** [comment]
Python 3,
see https://github.com/kerel-fs/ogn-rdb/blob/master/mkreceiverjson.py#L1

**Comment by pyrog** [comment]
Oops.

On macOS there is a lot of Python version installed 😞

So we must specify **pip3**:
`pip3 install -r requirements.txt`

**Comment by kerel-fs** [comment]
No. E.g. in a virtual environment with python3 `pip` is the right choice.
See also https://github.com/kerel-fs/ogn-rdb/blob/master/README.md#requirements
