### ISSUE TITLE
Receiver list is empty if aprs server glidern1 is down

### ISSUE THREAD

**Issue by kerel-fs** [kerel-fs/ogn-rdb#5]
Currently [glidern1](http://glidern1.glidernet.org:14501/) is down. Probably due to this, the receiver list is empty, although [glidern2](http://glidern2.glidernet.org:14501/) and [glidern3](http://glidern3.glidernet.org:14501/) are up and running.

**Comment by pyrog** [comment]
[glidern1/status.json](https://ogn.peanutpod.de/glidern1/status.json) contain an http error message that coudn't be interpretated correctly by [controllers.js](https://github.com/kerel-fs/ogn-rdb/blob/master/web/js/controllers.js)
