### ISSUE TITLE
Encode receivers.json in UTF-8

### ISSUE THREAD

**Issue by pyrog** [kerel-fs/ogn-rdb#8]
Accented characters are escaped in this form `\u00e9`.
JSON validator return: "[Invalid encoding, expecting UTF-8, UTF-16 or UTF-32.](http://www.freeformatter.com/json-validator.html)"

Reading (and I hope) editing this file is difficult.

**Comment by kerel-fs** [comment]
Can't reproduce: `The JSON input is valid according to RFC 4627 (JSON specfication).`

Manually editing this file is not recommended. If you want to edit data manually, I recommend a form-input.

**Comment by pyrog** [comment]
Sorry, I used another validator that accept URL. :confused:
https://jsonformatter.curiousconcept.com

See https://docs.python.org/3/library/json.html#character-encodings
